# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-28 04:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Idea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField(default=9)),
                ('title', models.CharField(max_length=140)),
                ('description', models.CharField(max_length=500)),
                ('status', models.IntegerField(default=0)),
                ('state', models.IntegerField(default=0)),
                ('create_date', models.DateTimeField(verbose_name='date_created')),
                ('modified_date', models.DateTimeField(verbose_name='date_modified')),
            ],
        ),
    ]
